### ISSUE TITLE
Wrong progname in `python -m wait_for_it --help` output

### ISSUE THREAD

**Issue by hartwork** [clarketm/wait-for-it#10]
Hi!

It reads `__main__` in usage here (and during tests), see:
```console
# python -m wait_for_it --help | head -n1
Usage: __main__.py [OPTIONS] [COMMANDS]...
```
I tried changing `@click.command()` to `@click.command(name='wait-for-it')` but it has no effect. I'm rather new to click, do you have any pointers on this for me?

Thanks and best, Sebastian

**Comment by clarketm** [comment]
Not off the top of my head but I did a little digging and there appears to be a `prog_name` argument that can be specified in `__main__.py` ([ref](https://github.com/pallets/click/issues/1399)) to fix this.

```diff
from wait_for_it.wait_for_it import cli

- cli()
+ cli(prog_name='python -m wait-for-it')
```
```console
# python -m wait_for_it --help | head -n1
Usage: python -m wait-for-it [OPTIONS] [COMMANDS]...
```

**Comment by hartwork** [comment]
Okay cool — awesome!
