### ISSUE TITLE
Bug: only works with http services

### ISSUE THREAD

**Issue by cal97g** [clarketm/wait-for-it#2]
```
def connect(service, timeout):
    scheme, _, host = service.rpartition(r"//")
    url = urlparse(f"{scheme}//{host}", scheme="http")

    host = url.hostname
    port = url.port or (443 if url.scheme == "https" else 80)

    friendly_name = f"{host}:{port}"
```

This code means that `mypostgres:5432` gets butchered into `None:80`.

We shouldn't care about the scheme or about guessing the port. If the user is too incompetent to know that https runs on port 443 and http on port 80 then that's on them; right?

**Comment by clarketm** [comment]
@cal97g
> This code means that mypostgres:5432 gets butchered into None:80.

That is not correct. The `hostname` will be resolved just fine in that example. 

```
wait-for-it -s mypostgres:5432
> waiting 15 seconds for mypostgres:5432
```

Furthermore, this tool **does** work with non-http services. The purpose of the `scheme` and `urlparse` in the code it to *default* the port if one is *not defined*. 

**e.g.**

|  input | reslved  |
|---|---|
| `wait-for-it -s www.google.com`  | `www.google.com:80` (*default* **http**)  |
| `wait-for-it -s http://www.google.com`  | `www.google.com:80` (*default* **http**)  |
| `wait-for-it -s www.google.com:112`  | `www.google.com:112`  |
| `wait-for-it -s https://www.google.com`  | `www.google.com:443` (*default* **https**)   |
| `wait-for-it -s mypostgres:5432`  | `mypostgres:5432`  |
