### ISSUE TITLE
Forwarding exit code from command executed

### ISSUE THREAD

**Issue by m-aciek** [clarketm/wait-for-it#3]
Hi, thank you for publishing this. It would be nice if wait-for-it would forward exit code of underlying process, where command has been executed. Job in our pipeline was invoked through wait-for-it and we weren't receiving the feedback, because job was treated as successful every time, so we had to fork and vendor the library.

**Comment by clarketm** [comment]
Thanks for the issue. I agree this is a valuable feature! I will merge in https://github.com/clarketm/wait-for-it/pull/4 and cut a release.

**Comment by m-aciek** [comment]
@clarketm Thank you!
