### ISSUE TITLE
Add support for comma separated URLs

### ISSUE THREAD

**Issue by hyzyla** [clarketm/wait-for-it#48]
It's very [common](https://jaceklaskowski.gitbooks.io/apache-kafka/content/kafka-properties-bootstrap-servers.html) to have an environment variable with a list of URLs separated by command for Kafka servers. For example:

```python
BOOTSTRAP_SERVERS = 'kafka-0:9092,kafka-1:9092,kafka-2:9092'
```

I would like to propose adding an additional parameter by which wait-for-it should split the URL. 
```shell
wait-for-it --service ${BOOTSTRAP_SERVERS} --url-separator ","
```

**Comment by SamirPS** [comment]
Hi,

Do you know where to add this in the source code ?

**Comment by hartwork** [comment]
@hyzyla your problem can be solved using Bash Arrays, e.g.:
```console
# BOOTSTRAP_SERVERS=kafka-0:9092,kafka-1:9092,kafka-2:9092
# BOOTSTRAP_SERVERS=( $(IFS=,; echo ${BOOTSTRAP_SERVERS}) )
# echo "${BOOTSTRAP_SERVERS[@]}"
kafka-0:9092 kafka-1:9092 kafka-2:9092
# echo "${#BOOTSTRAP_SERVERS[@]}"
3
```
So it would probably be waste to add support for this right into wait-for-it.

**Comment by hartwork** [comment]
@clarketm are you okay with me closing this as "wont fix"?

**Comment by hyzyla** [comment]
> @hyzyla your problem can be solved using Bash Arrays, e.g.:

Thanks. But I came to that library from ugly shell scripts, like wait-for-it.sh. And I like the simplicity that it gives for various types of URLs – just pass any URL and it works.  This library is often used to wait for the services in Python environments. For my own statistics: Redis, Kafka, Rabbitmq, and PostgreSQL are the most common third-party service that are used with Python. My request is to cover typical use case with the Kafka server.

**Comment by hartwork** [comment]
@hyzyla I don't see putting multiple host-port tuples into a single `--service` a good fit: It doesn't fit the model. And it goes against the Unix philosophy's key point:

> *Make each program do one thing well. To do a new job, build afresh rather than complicate old programs by adding new "features".*
> https://en.wikipedia.org/wiki/Unix_philosophy#Origin

There are places where violating that principle makes good sense: an IDE or a web browser; but not wait-for-it.
We have the shell for transformations like that. If you don't like Bash Arrays, here's another way:

```console
# sed -e 's|,| |g' -e 's| | --service |g' <<<" ${BOOTSTRAP_SERVERS}" | xargs echo wait-for-it
wait-for-it --service kafka-0:9092 --service kafka-1:9092 --service kafka-2:9092
```

No reason to rebuild the wheel.
