### ISSUE TITLE
Wasting 1 second per service on purpose?

### ISSUE THREAD

**Issue by hartwork** [clarketm/wait-for-it#5]
Hi, thanks for sharing this software as software libre! :pray: 

I found that `time.sleep(1)` at https://github.com/clarketm/wait-for-it/blob/c742b6205c54620d2a4271c1606cb2ff5ea8cbb7/wait_for_it/wait_for_it.py#L90 is always executed, even when the service was found and `break` jumped out of the loop. It seems like wastng time to me — is this on purpose? I have this patch in mind:

```diff
diff --git a/wait_for_it/wait_for_it.py b/wait_for_it/wait_for_it.py
index f9162a8..8c98eb6 100644
--- a/wait_for_it/wait_for_it.py
+++ b/wait_for_it/wait_for_it.py
@@ -86,8 +86,7 @@ def connect(service, timeout):
                 break
         except socket.gaierror:
             pass
-        finally:
-            time.sleep(1)
+        time.sleep(1)
 
     signal.alarm(0)
 ```

Happy to turn that into a pull request if welcome.

What do you think?

**Comment by clarketm** [comment]
> is always executed, even when the service was found and `break` jumped out of the loop. It seems like wastng time to me — is this on purpose? 

Good catch! No, this is not intentional and the patch you propose is a good optimization. 

> Happy to turn that into a pull request if welcome.

That would be awesome, thank you!
